services:
  app:
    image: ghcr.io/fatihjr9/todo-api_express:latest
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: "mysql://root:@db:3306/exp_dc"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: exp_dc
    ports:
      - "3306:3306"
