services:
  app:
    container_name: todoapiexp
    image: todoapiexp
    build:
      context: ./todoapiexp
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: "mysql://root:@localhost:3306/exp_dc"
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: exp_dc
    ports:
      - "3306:3306"
