version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: exp_dc
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: "mysql://root:@host.docker.internal:3306/exp_dc"
    depends_on:
      - db
